### ISSUE TITLE
null reference exception on underlyingSocket

### ISSUE THREAD

**Issue by ToeFrog** [Inumedia/Slack#4]
On line 47 of SlackSocketClient.cs after authenticating, underlyingSocket is null and throws a null reference exception.

**Comment by Inumedia** [comment]
This is a prototype project hacked together with no long term intent on maintaining it.

If this is an issue with the underlying API can you close this and log it with that project? It can be found at https://github.com/Inumedia/SlackAPI

Thanks :)
