### ISSUE TITLE
email not getting through the authentication

### ISSUE THREAD

**Issue by bilsou** [Inumedia/Slack#5]
Hi, just been playing around with your Slack implementation and unfortunately couldn't get past the email login screen. It seems the authentication fails. Any update to make to the code to make the thing work ?
Thanks

**Comment by Inumedia** [comment]
Hi @bilal-sou ,

This implementation no longer works as Slack has changed their underlying authentication system to be based on OAuth only. This was an extremely old prototype just for testing out my https://github.com/Inumedia/SlackAPI project.

**Comment by bilsou** [comment]
Hi @Inumedia 

That's what I was afraid of as it's been 2 years already. I was just looking at a possibility to make a full fledge UWP app and found this repo. 
Your SlackAPI looks really great, is it up to date for production code ? 
If yes i will start playing around with it and start doing some UI after.

**Comment by Inumedia** [comment]
I've used it pretty extensively and there's a NuGet setup for it. I also (mostly) actively accept pull requests.

**Comment by bilsou** [comment]
Thanks a lot, your lib is gonna be more than useful. Will come back to you if I have any question regarding the API's doc which looks a bit sparse;).

**Comment by Inumedia** [comment]
Yeah, I haven't had a whole lot of time to dedicate to putting up documentation. You're welcome to contribute to it if you want or ask questions if you need help figuring stuff out. There is a couple examples on the Wiki :smile:
